### PR TITLE
Add the omitted project_id for sqlite

### LINKED ISSUE #9: Removed projects still in starred list (without title)
When i remove a starred project the entry without a title stays in the starred projects list and can't be removed

### PR DESCRIPTION
**Pull request by alfredbuehler**
The plugin installation failed without this line. 
Fixes #9.

### CODE REVIEW

**Comment by aljawaid** [comment]
Does the same need doing for mysql? as that wont install either

**Comment by aljawaid** [comment]
> Does the same need doing for mysql? as that wont install either

actually, manually creating the table installs the plugin, but thats not the correct way

**Comment by alfredbuehler** [comment]
> Does the same need doing for mysql? as that wont install either

The project_id line was only missing for SQLite. I don't have any Postgres at hand, but for MySQL, I could have a look.

**Comment by alfredbuehler** [comment]
@aljawaid Meanwhile I could check it on the MySQL version. But here the plugin installs without any problem, and the created DB table looks correct.
The issue might be, that they changed the schema, but didn't increase the schema version. As a workaround, I recommend, uninstall the plugin, remove the table _starred_projects_ end the related record in table _plugin_schema_versions_. Subsequently, install should work as expected.

**Comment by aljawaid** [comment]
> @aljawaid Meanwhile I could check it on the MySQL version. But here the plugin installs without any problem, and the created DB table looks correct. The issue might be, that they changed the schema, but didn't increase the schema version. As a workaround, I recommend, uninstall the plugin, remove the table _starred_projects_ end the related record in table _plugin_schema_versions_. Subsequently, install should work as expected.

this fixed the installation.... thanks for this

**Comment by jajm** [comment]
I don't think it fixes #9 but it does fix plugin installation on sqlite kanboards.
Thanks

**Comment by alfredbuehler** [comment]
> I don't think it fixes #9

Well, it really does, at least for completely fresh installations. Otherwise, you'll need some [manual work](https://github.com/biblibre/kanboard-plugin-StarredProjects/pull/14#issuecomment-1307705058), or a new version including a proper schema upgrade, to add the two missing constraints.

**Comment by jajm** [comment]
On a completely fresh installation the plugin installation process would have failed. How can you have a problem with the plugin without the plugin ?
I'm probably missing something here, but it doesn't matter, as long as it works :)

> Otherwise, you'll need some manual work, or a new version including a proper schema upgrade, to add the two missing constraints.

You're right, database schema changes were not handled correctly so uninstalling/reinstalling the plugin is needed when upgrading.

**Comment by alfredbuehler** [comment]
> uninstalling/reinstalling the plugin is needed when upgrading.

No, this is not enough. The DB table is not dropped by uninstalling, it won’t be touched by reinstalling. See my cited post above.

**Pull request merged**
